const kCountryOptions = [
  'Philippines',
  'Argentina',
  'Australia',
  'Austria',
  'Bahrain',
  'Bangladesh',
  'Belgium',
  'Brazil',
  'Brunei',
  'Cambodia',
  'Canada',
  'China',
  'Colombia',
  'CIS',
  'Denmark',
  'Egypt',
  'Finland',
  'France',
  'Germany',
  'Greece',
  'Guam',
  'Hong Kong',
  'India',
  'Indonesia',
  'Iran',
  'Ireland',
  'Israel',
  'Italy',
  'Japan',
  'Jordan',
  'Korea',
  'Kuwait',
  'Laos',
  'Luxembourg',
  'Malaysia',
  'Mexico',
  'Myanmar',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nigeria',
  'Norway',
  'Pakistan',
  'Papua NG',
  'Peru',
  'Poland',
  'Portugal',
  'Russia',
  'Saudi Arabia',
  'Singapore',
  'South Africa',
  'Spain',
  'Sri Lanka',
  'Sweden',
  'Switzerland',
  'Taiwan',
  'Thailand',
  'Serbia & Montenegro',
  'UAE',
  'United Kingdom',
  'USA',
  'Venezuela',
  'Vietnam',
  'Others',
];

const _countryToReportFormat = {
  'CIS': 'COMMONWEALTH OF INDEPENDENT STATES',
  'Hong Kong': 'HONGKONG',
  'Papua NG': 'PAPUA NEW GUINEA',
  'Serbia & Montenegro': 'UNION OF SERBIA AND MONTENEGRO',
  'UAE': 'UNITED ARAB EMIRATES',
};

const _reportFormatToCountry = {
  'COMMONWEALTH OF INDEPENDENT STATES': 'CIS',
  'HONGKONG': 'Hong Kong',
  'PAPUA NEW GUINEA': 'Papua NG',
  'UNION OF SERBIA AND MONTENEGRO': 'Serbia & Montenegro',
  'UNITED ARAB EMIRATES': 'UAE',
};

String mapToReportFormat(String country) =>
    _countryToReportFormat[country] ?? country;

String mapFromReportFormat(String country) =>
    _reportFormatToCountry[country] ?? country;
